export type PaletteColor = [number, number, number];

export type Config = {
  cols: number;
  rows: number;
  bandCount: number;
  scale: number;
  secondaryScale: number;
  drift: number;
  jitter: number;
  quantizeSteps: number;
  snapStrength: number;
  anisotropy: number;
  spikeChance: number;
  spikeIntensity: number;
  driftWaveAmp: number;
  driftWaveFreq: number;
  waveAmp: number;
  alphaBase: number;
  alphaGain: number;
  warpStrength: number;
  warpFrequency: number;
  trailStrength: number;
  dualLayerStrength: number;
  axisBlend: number;
  dynamicGlyphMix: number;
  chromaticAberration: number;
  radialBloom: number;
  blurAmount: number;
  sharpenAmount: number;
  colorTwist: number;
  embossStrength: number;
  rippleDistortion: number;
  layerBlend: number;
  style:
    | 'perlin'
    | 'ridged'
    | 'stripe'
    | 'worley'
    | 'curl'
    | 'cyber'
    | 'voronoi'
    | 'brick'
    | 'step'
    | 'glitch'
    | 'height'
    | 'perspective'
    | 'flight'
    | 'tunnel'
    | 'kaleido'
    | 'flow'
    | 'orbital'
    | 'cellular'
    | 'hearts'
    | 'anomaly'
    | 'checker'
    | 'hex_tiling'
    | 'burst'
    | 'isogrid'
    | 'constellation'
    | 'spiral'
    | 'circuit'
    | 'menger'
    | 'stepper'
    | 'quilt'
    | 'mosaic'
    | 'interference'
    | 'voronoi_outline'
    | 'scribe'
    | 'spiral_net'
    | 'herringbone'
    | 'ripple'
    | 'orbits'
    | 'flecktarn'
    | 'multicam'
    | 'digital'
    | 'tiger'
    | 'kryptek'
    | 'hex_camo'
    | 'woodland'
    | 'akira'
    | 'lcl_hud'
    | 'ghost_hud'
    | 'bebop'
    | 'moire'
    | 'halftone'
    | 'topo'
    | 'storm_radar'
    | 'matrix_rain'
    | 'blueprint'
    | 'carbon'
    | 'paisley'
    | 'starburst'
    | 'radar_hud'
    | 'lv_monogram'
    | 'burberry'
    | 'gucci'
    | 'plaid'
    | 'lace'
    | 'ps2_bios'
    | 'devils_heel'
    | 'cheetah'
    | 'floral'
    | 'hemp'
    | 'berserk';
  glyphs: string[];
  palette: PaletteColor[];
  seed: number;
};

export type ParamDef = {
  key: keyof Config;
  label: string;
  min: number;
  max: number;
  step: number;
  integer?: boolean;
  affectsBand?: boolean;
  affectsGrid?: boolean;
  syncWorker?: boolean;
};
